# Generated by Django 4.2.6 on 2023-10-06 20:13

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0002_rename_user_userprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='thumbnail_200',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[None, 200], upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='thumbnail_400',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[None, 400], upload_to='thumbnails/'),
        ),
    ]
