# Generated by Django 4.2.6 on 2023-10-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0003_uploadimage_thumbnail_200_uploadimage_thumbnail_400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='thumbnail_200',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='thumbnail_400',
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='image_200',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails_200/'),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='image_300',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails_400/'),
        ),
    ]
