# Generated by Django 4.2.6 on 2023-10-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0004_remove_uploadimage_thumbnail_200_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='image_300',
            new_name='image_400',
        ),
    ]
