# Generated by Django 4.2.6 on 2023-10-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0005_rename_image_300_uploadimage_image_400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='image_200',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='image_400',
        ),
    ]
