# Generated by Django 4.2.6 on 2023-10-15 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0006_uploadimage_expiration_date_uploadimage_expired_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='expired_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
