# Generated by Django 4.2.6 on 2023-10-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0006_remove_uploadimage_image_200_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='img_200',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails_200/'),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='img_400',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails_400/'),
        ),
    ]
