# Generated by Django 4.2.6 on 2023-10-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0007_uploadimage_expired_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='expiration_date2',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
