# Generated by Django 4.2.6 on 2023-10-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0008_uploadimage_expiration_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='expiration_date2',
        ),
    ]
